const charterBookings = [
  // January 2025 Bookings
  {
    Passengers: 4,
    Occasion: "Birthday",
    "Additional Info": "Surprise party",
    Date: "2025-01-03",
    "Charter Length": "3 hours",
    Time: "15:30",
    "First Name": "Emily",
    "Last Name": "Johnson",
    Email: "emily.johnson@example.com",
    Phone: 4158198709,
    "Contact Mode": "Email",
    "Text Opt In": true,
    Type: "Find Yacht"
  },
  {
    Passengers: 6,
    Occasion: "Anniversary",
    "Additional Info": "Romantic setup",
    Date: "2025-01-08",
    "Charter Length": "4 hours",
    Time: "18:00",
    "First Name": "Michael",
    "Last Name": "Smith",
    Email: "michael.smith@example.com",
    Phone: 4159876543,
    "Contact Mode": "Phone",
    "Text Opt In": false,
    Type: "New Request"
  },
  {
    Passengers: 2,
    Occasion: "Proposal",
    "Additional Info": "Champagne and flowers",
    Date: "2025-01-12",
    "Charter Length": "2 hours",
    Time: "17:00",
    "First Name": "David",
    "Last Name": "Martinez",
    Email: "david.martinez@example.com",
    Phone: 4156543210,
    "Contact Mode": "Text",
    "Text Opt In": true,
    Type: "Find Yacht"
  },
  {
    Passengers: 8,
    Occasion: "Corporate Event",
    "Additional Info": "Need projector setup",
    Date: "2025-01-16",
    "Charter Length": "5 hours",
    Time: "12:00",
    "First Name": "Sarah",
    "Last Name": "Williams",
    Email: "sarah.williams@example.com",
    Phone: 4157654321,
    "Contact Mode": "Email",
    "Text Opt In": false,
    Type: "New Request"
  },
  {
    Passengers: 3,
    Occasion: "Casual Getaway",
    "Additional Info": "Music system required",
    Date: "2025-01-19",
    "Charter Length": "3 hours",
    Time: "14:00",
    "First Name": "Jessica",
    "Last Name": "Brown",
    Email: "jessica.brown@example.com",
    Phone: 4158745632,
    "Contact Mode": "Text",
    "Text Opt In": true,
    Type: "Find Yacht"
  },
  {
    Passengers: 5,
    Occasion: "Family Reunion",
    "Additional Info": "Gluten-free snacks",
    Date: "2025-01-22",
    "Charter Length": "4 hours",
    Time: "16:00",
    "First Name": "Daniel",
    "Last Name": "Harris",
    Email: "daniel.harris@example.com",
    Phone: 4159988776,
    "Contact Mode": "Phone",
    "Text Opt In": false,
    Type: "New Request"
  },
  {
    Passengers: 7,
    Occasion: "Graduation Party",
    "Additional Info": "DJ setup requested",
    Date: "2025-01-26",
    "Charter Length": "5 hours",
    Time: "19:00",
    "First Name": "Christopher",
    "Last Name": "Garcia",
    Email: "chris.garcia@example.com",
    Phone: 4156758493,
    "Contact Mode": "Email",
    "Text Opt In": true,
    Type: "Find Yacht"
  },
  {
    Passengers: 4,
    Occasion: "Engagement",
    "Additional Info": "Candlelight dinner",
    Date: "2025-01-30",
    "Charter Length": "3 hours",
    Time: "20:00",
    "First Name": "Amanda",
    "Last Name": "Lopez",
    Email: "amanda.lopez@example.com",
    Phone: 4158796453,
    "Contact Mode": "Text",
    "Text Opt In": false,
    Type: "New Request"
  },
  // February 2025 Bookings
  {
    Passengers: 5,
    Occasion: "Valentine's Day",
    "Additional Info": "Romantic setup with roses",
    Date: "2025-02-02",
    "Charter Length": "3 hours",
    Time: "18:30",
    "First Name": "Olivia",
    "Last Name": "Roberts",
    Email: "olivia.roberts@example.com",
    Phone: 4159123456,
    "Contact Mode": "Email",
    "Text Opt In": true,
    Type: "Find Yacht"
  },
  {
    Passengers: 8,
    Occasion: "Birthday Party",
    "Additional Info": "Cake and decorations included",
    Date: "2025-02-06",
    "Charter Length": "4 hours",
    Time: "14:00",
    "First Name": "Ethan",
    "Last Name": "Davis",
    Email: "ethan.davis@example.com",
    Phone: 4158234567,
    "Contact Mode": "Phone",
    "Text Opt In": false,
    Type: "New Request"
  },
  {
    Passengers: 3,
    Occasion: "Casual Outing",
    "Additional Info": "Bring our own drinks",
    Date: "2025-02-10",
    "Charter Length": "2 hours",
    Time: "16:00",
    "First Name": "Sophia",
    "Last Name": "Martinez",
    Email: "sophia.martinez@example.com",
    Phone: 4157345678,
    "Contact Mode": "Text",
    "Text Opt In": true,
    Type: "Find Yacht"
  },
  {
    Passengers: 6,
    Occasion: "Corporate Retreat",
    "Additional Info": "Team-building activities",
    Date: "2025-02-14",
    "Charter Length": "5 hours",
    Time: "10:00",
    "First Name": "Liam",
    "Last Name": "Hernandez",
    Email: "liam.hernandez@example.com",
    Phone: 4156456789,
    "Contact Mode": "Email",
    "Text Opt In": false,
    Type: "New Request"
  },
  {
    Passengers: 2,
    Occasion: "Anniversary",
    "Additional Info": "Private dining request",
    Date: "2025-02-18",
    "Charter Length": "3 hours",
    Time: "19:30",
    "First Name": "Mia",
    "Last Name": "Lopez",
    Email: "mia.lopez@example.com",
    Phone: 4155567890,
    "Contact Mode": "Text",
    "Text Opt In": true,
    Type: "Find Yacht"
  },
  {
    Passengers: 7,
    Occasion: "Bachelor Party",
    "Additional Info": "Music and drinks needed",
    Date: "2025-02-22",
    "Charter Length": "4 hours",
    Time: "20:00",
    "First Name": "Noah",
    "Last Name": "Wilson",
    Email: "noah.wilson@example.com",
    Phone: 4154678901,
    "Contact Mode": "Phone",
    "Text Opt In": false,
    Type: "New Request"
  },
  {
    Passengers: 4,
    Occasion: "Family Gathering",
    "Additional Info": "Kid-friendly setup",
    Date: "2025-02-26",
    "Charter Length": "3 hours",
    Time: "13:00",
    "First Name": "Charlotte",
    "Last Name": "Anderson",
    Email: "charlotte.anderson@example.com",
    Phone: 4153789012,
    "Contact Mode": "Email",
    "Text Opt In": true,
    Type: "Find Yacht"
  },
  {
    Passengers: 5,
    Occasion: "Engagement",
    "Additional Info": "Sunset cruise",
    Date: "2025-02-28",
    "Charter Length": "3 hours",
    Time: "17:00",
    "First Name": "James",
    "Last Name": "Thomas",
    Email: "james.thomas@example.com",
    Phone: 4152890123,
    "Contact Mode": "Text",
    "Text Opt In": false,
    Type: "New Request"
  },
  // March 2025 Bookings
  {
    Passengers: 3,
    Occasion: "Spring Break",
    "Additional Info": "Snacks and drinks provided",
    Date: "2025-03-02",
    "Charter Length": "4 hours",
    Time: "11:00",
    "First Name": "Ava",
    "Last Name": "Jackson",
    Email: "ava.jackson@example.com",
    Phone: 4159123456,
    "Contact Mode": "Email",
    "Text Opt In": true,
    Type: "Find Yacht"
  },
  {
    Passengers: 6,
    Occasion: "Birthday Party",
    "Additional Info": "Live music performance",
    Date: "2025-03-05",
    "Charter Length": "5 hours",
    Time: "14:30",
    "First Name": "Liam",
    "Last Name": "Miller",
    Email: "liam.miller@example.com",
    Phone: 4158234567,
    "Contact Mode": "Phone",
    "Text Opt In": false,
    Type: "New Request"
  },
  {
    Passengers: 4,
    Occasion: "Wedding",
    "Additional Info": "Wedding vows on the deck",
    Date: "2025-03-08",
    "Charter Length": "3 hours",
    Time: "16:00",
    "First Name": "Sophia",
    "Last Name": "Taylor",
    Email: "sophia.taylor@example.com",
    Phone: 4157345678,
    "Contact Mode": "Text",
    "Text Opt In": true,
    Type: "Find Yacht"
  },
  {
    Passengers: 2,
    Occasion: "Proposal",
    "Additional Info": "Dinner setup on board",
    Date: "2025-03-12",
    "Charter Length": "2 hours",
    Time: "18:00",
    "First Name": "Ethan",
    "Last Name": "Garcia",
    Email: "ethan.garcia@example.com",
    Phone: 4156456789,
    "Contact Mode": "Email",
    "Text Opt In": false,
    Type: "New Request"
  },
  {
    Passengers: 8,
    Occasion: "Corporate Event",
    "Additional Info": "Team-building activities",
    Date: "2025-03-15",
    "Charter Length": "6 hours",
    Time: "10:00",
    "First Name": "Emily",
    "Last Name": "Wilson",
    Email: "emily.wilson@example.com",
    Phone: 4155567890,
    "Contact Mode": "Phone",
    "Text Opt In": true,
    Type: "Find Yacht"
  },
  {
    Passengers: 7,
    Occasion: "Family Get-Together",
    "Additional Info": "Kid-friendly entertainment",
    Date: "2025-03-18",
    "Charter Length": "4 hours",
    Time: "12:00",
    "First Name": "Lucas",
    "Last Name": "Anderson",
    Email: "lucas.anderson@example.com",
    Phone: 4154678901,
    "Contact Mode": "Text",
    "Text Opt In": false,
    Type: "New Request"
  },
  {
    Passengers: 5,
    Occasion: "Graduation Celebration",
    "Additional Info": "Cake and decorations",
    Date: "2025-03-22",
    "Charter Length": "3 hours",
    Time: "15:30",
    "First Name": "Mia",
    "Last Name": "Johnson",
    Email: "mia.johnson@example.com",
    Phone: 4153789012,
    "Contact Mode": "Email",
    "Text Opt In": true,
    Type: "Find Yacht"
  },
  {
    Passengers: 6,
    Occasion: "Anniversary",
    "Additional Info": "Champagne and flowers",
    Date: "2025-03-26",
    "Charter Length": "4 hours",
    Time: "17:00",
    "First Name": "Olivia",
    "Last Name": "Brown",
    Email: "olivia.brown@example.com",
    Phone: 4152890123,
    "Contact Mode": "Phone",
    "Text Opt In": false,
    Type: "New Request"
  }
]
